service: sentiment

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    CAPI_KEY: "${file(./serverless.env.yml):CAPI_API_KEY}"
    TEST: "${file(./serverless.env.yml):TEST}"
  stackTags:
    environment: p
    teamDL: ftlabs@ft.com
    systemCode: ftlabs-sentiment
  iamRoleStatements:
    - Effect: Allow
      Action:
        - comprehend:DetectKeyPhrases
        - comprehend:DetectEntities
        - comprehend:DetectSentiment
        - comprehend:BatchDetectKeyPhrases
        - comprehend:BatchDetectEntities
      Resource: "*"

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: ftlabs-sentiment
          method: any
